/*=============================================================================
 
indirect_indexing.inc

#included in test_MDArray.cpp

Peter Hakel
Los Alamos National Laboratory
XCP-5 group

Created on 7 July 2015
Last modified on 1 April 2023

Copyright (c) 2015, Triad National Security, LLC.
All rights reserved.
Use of this source code is governed by the BSD 3-Clause License.
See top-level license.txt file for full license text.

CODE NAME:  FESTR, Version 0.8 (C15068)
Classification Review Number: LA-CC-15-045
Export Control Classification Number (ECCN): EAR99
B&R Code:  DP1516090

=============================================================================*/

MDIndex dim{4, 2, 1, 3}; // dimensions

//  end indirect_indexing.inc
